export const locations = [
  '24 Agosto',
  'Aeroporto',
  'Aliados',
  'Alto de Pega',
  'Araújo',
  'Árvore',
  'Azurara',
  'Baguim',
  'Bolhão',
  'Botica',
  'Brito Capelo',
  'Câmara de Gaia',
  'Câmara de Matosinhos',
  'Campainha',
  'Campanhã',
  'Cândido dos Reis',
  'Carolina Michaelis',
  'Carreira',
  'Casa da Música',
  'Castêlo da Maia',
  'Combatentes',
  'Contumil',
  'Crestins',
  'Custió',
  'Custóias',
  'D. João II',
  'Espaço Natureza',
  'Esposade',
  'Estádio do Dragão',
  'Estádio do Mar',
  'Fânzeres ',
  'Faria Guimarães',
  'Fonte do Cuco',
  'Fórum Maia',
  'Francos',
  'General Torres',
  'Heroísmo',
  'Hospital São João',
  'IPO',
  'ISMAI',
  'Jardim do Morro',
  'João de Deus',
  'Lapa',
  'Levada',
  'Lidador',
  'Mandim',
  'Marquês',
  'Matosinhos Sul',
  'Mercado',
  'Mindelo',
  'Modivas Centro',
  'Modivas Sul',
  'Nasoni',
  'Nau Vitória ',
  'Parque de Real',
  'Parque Maia',
  'Pedras Rubras',
  'Pedro Hispano',
  'Pias',
  'Polo Universitário',
  'Porta-Fronhas',
  'Póvoa de Varzim',
  'Ramalde',
  'Rio Tinto',
  'S. Brás',
  'Salgueiros',
  'Santa Clara',
  'Santo Ovídio',
  'São Bento',
  'Senhora da Hora',
  'Sete Bicas',
  'Sr. de Matosinhos',
  'Trindade',
  'Varziela',
  'Vasco da Gama',
  'VC Fashion Outlet – Modivas',
  'Venda Nova',
  'Verdes',
  'Vila do Conde',
  'Vilar do Pinheiro',
  'Viso',
  'Zona Industrial'
];
