export const stations = {
    'A': [
        'Senhor de Matosinhos',
        'Mercado',
        'Brito Capelo',
        'Matosinhos Sul',
        'Câmara Matosinhos',
        'Parque Real',
        'Pedro Hispano',
        'Estádio do Mar',
        'Vasco da Gama',
        'Senhora da Hora',
        'Sete Bicas',
        'Via Rápida/Viso',
        'Ramalde',
        'Francos',
        'Casa da Música',
        'Carolina Michaelis',
        'Lapa',
        'Trindade',
        'Bolhão',
        'Campo 24 Agosto',
        'Heroísmo',
        'Campanhã',
        'Estádio do Dragão'
    ],
    'B': [
        'Póvoa de Varzim',
        'São Brás',
        'Portas Fronhas',
        'Alto de Pega',
        'Vila do Conde',
        'Santa Clara',
        'Azurara',
        'Árvore',
        'Varziela',
        'Espaço Natureza',
        'Mindelo',
        'VC Fashion Outlet/Modivas',
        'Modivas Centro',
        'Modivas Sul',
        'Vilar do Pinheiro',
        'Lidador',
        'Pedras Rubras',
        'Verdes',
        'Crestins',
        'Esposade',
        'Custóias',
        'Fonte do Cuco',
        'Senhora da Hora',
        'Sete Bicas',
        'Via Rápida/Viso',
        'Ramalde',
        'Francos',
        'Casa da Música',
        'Carolina Michaelis',
        'Lapa',
        'Trindade',
        'Bolhão',
        'Campo 24 Agosto',
        'Heroísmo',
        'Campanhã',
        'Estádio do Dragão'
    ],
    'C': [
        'ISMAI',
        'Castêlo da Maia',
        'Mandim',
        'Zona Industrial',
        'Fórum Maia',
        'Parque Maia',
        'Custió',
        'Araújo',
        'Pias',
        'Cândido dos Reis',
        'Fonte do Cuco',
        'Senhora da Hora',
        'Sete Bicas',
        'Via Rápida/Viso',
        'Ramalde',
        'Francos',
        'Casa da Música',
        'Carolina Michaelis',
        'Lapa',
        'Trindade',
        'Bolhão',
        'Campo 24 Agosto',
        'Heroísmo',
        'Campanhã'
    ],
    'D': [
        'Hospital São João',
        'IPO',
        'Pólo Universitário',
        'Salgueiros',
        'Combatentes',
        'Marquês',
        'Faria Guimarães',
        'Trindade',
        'Aliados',
        'São Bento',
        'Jardim do Morro',
        'General Torres',
        'Câmara Gaia',
        'João de Deus',
        'D. João II',
        'Santo Ovídio'
    ],
    'E': [
        'Aeroporto',
        'Botica',
        'Verdes',
        'Crestins',
        'Esposade',
        'Custóias',
        'Fonte do Cuco',
        'Senhora da Hora',
        'Sete Bicas',
        'Via Rápida/Viso',
        'Ramalde',
        'Francos',
        'Casa da Música',
        'Carolina Michaelis',
        'Lapa',
        'Trindade',
        'Bolhão',
        'Campo 24 Agosto',
        'Heroísmo',
        'Campanhã',
        'Estádio do Dragão'
    ],
    'F': [
        'Senhora da Hora',
        'Sete Bicas',
        'Via Rápida/Viso',
        'Ramalde',
        'Francos',
        'Casa da Música',
        'Carolina Michaelis',
        'Lapa',
        'Trindade',
        'Bolhão',
        'Campo 24 Agosto',
        'Heroísmo',
        'Campanhã',
        'Estádio do Dragão',
        'Contumil',
        'Nasoni',
        'Nau Vitória',
        'Levada',
        'Rio Tinto',
        'Campainha',
        'Baguim',
        'Carreira',
        'Venda Nova',
        'Fânzeres'

    ]
}